spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/transferdb
    username: transfer
    password: transfer
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
server:
  port: 8080
  error:
    include-message: always
